version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
